global:
  scrape_interval:     15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'yz-org1.yzchain.org'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.29.0.1:14321']
  - job_name: 'yz-org2.yzchain.org'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.29.0.1:14322']
  - job_name: 'yz-org3.yzchain.org'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.29.0.1:14323']
  - job_name: 'yz-org4.yzchain.org'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.29.0.1:14324']


remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"
